/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TopicsIndexRouteImport } from './routes/topics.index'
import { Route as QuizzesIndexRouteImport } from './routes/quizzes.index'
import { Route as TopicsTopicIdRouteImport } from './routes/topics.$topicId'
import { Route as QuizzesQuizIdRouteImport } from './routes/quizzes.$quizId'
import { Route as TopicsTopicIdModulesModuleIdRouteImport } from './routes/topics.$topicId.modules.$moduleId'
import { Route as TopicsTopicIdFinalExamLevelIdRouteImport } from './routes/topics.$topicId.final-exam.$levelId'
import { Route as TopicsTopicIdModulesModuleIdExamRouteImport } from './routes/topics.$topicId.modules.$moduleId.exam'
import { Route as TopicsTopicIdModulesModuleIdQuizQuizIdRouteImport } from './routes/topics.$topicId.modules.$moduleId.quiz.$quizId'

const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TopicsIndexRoute = TopicsIndexRouteImport.update({
  id: '/topics/',
  path: '/topics/',
  getParentRoute: () => rootRouteImport,
} as any)
const QuizzesIndexRoute = QuizzesIndexRouteImport.update({
  id: '/quizzes/',
  path: '/quizzes/',
  getParentRoute: () => rootRouteImport,
} as any)
const TopicsTopicIdRoute = TopicsTopicIdRouteImport.update({
  id: '/topics/$topicId',
  path: '/topics/$topicId',
  getParentRoute: () => rootRouteImport,
} as any)
const QuizzesQuizIdRoute = QuizzesQuizIdRouteImport.update({
  id: '/quizzes/$quizId',
  path: '/quizzes/$quizId',
  getParentRoute: () => rootRouteImport,
} as any)
const TopicsTopicIdModulesModuleIdRoute =
  TopicsTopicIdModulesModuleIdRouteImport.update({
    id: '/modules/$moduleId',
    path: '/modules/$moduleId',
    getParentRoute: () => TopicsTopicIdRoute,
  } as any)
const TopicsTopicIdFinalExamLevelIdRoute =
  TopicsTopicIdFinalExamLevelIdRouteImport.update({
    id: '/final-exam/$levelId',
    path: '/final-exam/$levelId',
    getParentRoute: () => TopicsTopicIdRoute,
  } as any)
const TopicsTopicIdModulesModuleIdExamRoute =
  TopicsTopicIdModulesModuleIdExamRouteImport.update({
    id: '/exam',
    path: '/exam',
    getParentRoute: () => TopicsTopicIdModulesModuleIdRoute,
  } as any)
const TopicsTopicIdModulesModuleIdQuizQuizIdRoute =
  TopicsTopicIdModulesModuleIdQuizQuizIdRouteImport.update({
    id: '/quiz/$quizId',
    path: '/quiz/$quizId',
    getParentRoute: () => TopicsTopicIdModulesModuleIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/profile': typeof ProfileRoute
  '/quizzes/$quizId': typeof QuizzesQuizIdRoute
  '/topics/$topicId': typeof TopicsTopicIdRouteWithChildren
  '/quizzes/': typeof QuizzesIndexRoute
  '/topics/': typeof TopicsIndexRoute
  '/topics/$topicId/final-exam/$levelId': typeof TopicsTopicIdFinalExamLevelIdRoute
  '/topics/$topicId/modules/$moduleId': typeof TopicsTopicIdModulesModuleIdRouteWithChildren
  '/topics/$topicId/modules/$moduleId/exam': typeof TopicsTopicIdModulesModuleIdExamRoute
  '/topics/$topicId/modules/$moduleId/quiz/$quizId': typeof TopicsTopicIdModulesModuleIdQuizQuizIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/profile': typeof ProfileRoute
  '/quizzes/$quizId': typeof QuizzesQuizIdRoute
  '/topics/$topicId': typeof TopicsTopicIdRouteWithChildren
  '/quizzes': typeof QuizzesIndexRoute
  '/topics': typeof TopicsIndexRoute
  '/topics/$topicId/final-exam/$levelId': typeof TopicsTopicIdFinalExamLevelIdRoute
  '/topics/$topicId/modules/$moduleId': typeof TopicsTopicIdModulesModuleIdRouteWithChildren
  '/topics/$topicId/modules/$moduleId/exam': typeof TopicsTopicIdModulesModuleIdExamRoute
  '/topics/$topicId/modules/$moduleId/quiz/$quizId': typeof TopicsTopicIdModulesModuleIdQuizQuizIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/profile': typeof ProfileRoute
  '/quizzes/$quizId': typeof QuizzesQuizIdRoute
  '/topics/$topicId': typeof TopicsTopicIdRouteWithChildren
  '/quizzes/': typeof QuizzesIndexRoute
  '/topics/': typeof TopicsIndexRoute
  '/topics/$topicId/final-exam/$levelId': typeof TopicsTopicIdFinalExamLevelIdRoute
  '/topics/$topicId/modules/$moduleId': typeof TopicsTopicIdModulesModuleIdRouteWithChildren
  '/topics/$topicId/modules/$moduleId/exam': typeof TopicsTopicIdModulesModuleIdExamRoute
  '/topics/$topicId/modules/$moduleId/quiz/$quizId': typeof TopicsTopicIdModulesModuleIdQuizQuizIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/profile'
    | '/quizzes/$quizId'
    | '/topics/$topicId'
    | '/quizzes/'
    | '/topics/'
    | '/topics/$topicId/final-exam/$levelId'
    | '/topics/$topicId/modules/$moduleId'
    | '/topics/$topicId/modules/$moduleId/exam'
    | '/topics/$topicId/modules/$moduleId/quiz/$quizId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/profile'
    | '/quizzes/$quizId'
    | '/topics/$topicId'
    | '/quizzes'
    | '/topics'
    | '/topics/$topicId/final-exam/$levelId'
    | '/topics/$topicId/modules/$moduleId'
    | '/topics/$topicId/modules/$moduleId/exam'
    | '/topics/$topicId/modules/$moduleId/quiz/$quizId'
  id:
    | '__root__'
    | '/'
    | '/profile'
    | '/quizzes/$quizId'
    | '/topics/$topicId'
    | '/quizzes/'
    | '/topics/'
    | '/topics/$topicId/final-exam/$levelId'
    | '/topics/$topicId/modules/$moduleId'
    | '/topics/$topicId/modules/$moduleId/exam'
    | '/topics/$topicId/modules/$moduleId/quiz/$quizId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ProfileRoute: typeof ProfileRoute
  QuizzesQuizIdRoute: typeof QuizzesQuizIdRoute
  TopicsTopicIdRoute: typeof TopicsTopicIdRouteWithChildren
  QuizzesIndexRoute: typeof QuizzesIndexRoute
  TopicsIndexRoute: typeof TopicsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/topics/': {
      id: '/topics/'
      path: '/topics'
      fullPath: '/topics/'
      preLoaderRoute: typeof TopicsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/quizzes/': {
      id: '/quizzes/'
      path: '/quizzes'
      fullPath: '/quizzes/'
      preLoaderRoute: typeof QuizzesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/topics/$topicId': {
      id: '/topics/$topicId'
      path: '/topics/$topicId'
      fullPath: '/topics/$topicId'
      preLoaderRoute: typeof TopicsTopicIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/quizzes/$quizId': {
      id: '/quizzes/$quizId'
      path: '/quizzes/$quizId'
      fullPath: '/quizzes/$quizId'
      preLoaderRoute: typeof QuizzesQuizIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/topics/$topicId/modules/$moduleId': {
      id: '/topics/$topicId/modules/$moduleId'
      path: '/modules/$moduleId'
      fullPath: '/topics/$topicId/modules/$moduleId'
      preLoaderRoute: typeof TopicsTopicIdModulesModuleIdRouteImport
      parentRoute: typeof TopicsTopicIdRoute
    }
    '/topics/$topicId/final-exam/$levelId': {
      id: '/topics/$topicId/final-exam/$levelId'
      path: '/final-exam/$levelId'
      fullPath: '/topics/$topicId/final-exam/$levelId'
      preLoaderRoute: typeof TopicsTopicIdFinalExamLevelIdRouteImport
      parentRoute: typeof TopicsTopicIdRoute
    }
    '/topics/$topicId/modules/$moduleId/exam': {
      id: '/topics/$topicId/modules/$moduleId/exam'
      path: '/exam'
      fullPath: '/topics/$topicId/modules/$moduleId/exam'
      preLoaderRoute: typeof TopicsTopicIdModulesModuleIdExamRouteImport
      parentRoute: typeof TopicsTopicIdModulesModuleIdRoute
    }
    '/topics/$topicId/modules/$moduleId/quiz/$quizId': {
      id: '/topics/$topicId/modules/$moduleId/quiz/$quizId'
      path: '/quiz/$quizId'
      fullPath: '/topics/$topicId/modules/$moduleId/quiz/$quizId'
      preLoaderRoute: typeof TopicsTopicIdModulesModuleIdQuizQuizIdRouteImport
      parentRoute: typeof TopicsTopicIdModulesModuleIdRoute
    }
  }
}

interface TopicsTopicIdModulesModuleIdRouteChildren {
  TopicsTopicIdModulesModuleIdExamRoute: typeof TopicsTopicIdModulesModuleIdExamRoute
  TopicsTopicIdModulesModuleIdQuizQuizIdRoute: typeof TopicsTopicIdModulesModuleIdQuizQuizIdRoute
}

const TopicsTopicIdModulesModuleIdRouteChildren: TopicsTopicIdModulesModuleIdRouteChildren =
  {
    TopicsTopicIdModulesModuleIdExamRoute:
      TopicsTopicIdModulesModuleIdExamRoute,
    TopicsTopicIdModulesModuleIdQuizQuizIdRoute:
      TopicsTopicIdModulesModuleIdQuizQuizIdRoute,
  }

const TopicsTopicIdModulesModuleIdRouteWithChildren =
  TopicsTopicIdModulesModuleIdRoute._addFileChildren(
    TopicsTopicIdModulesModuleIdRouteChildren,
  )

interface TopicsTopicIdRouteChildren {
  TopicsTopicIdFinalExamLevelIdRoute: typeof TopicsTopicIdFinalExamLevelIdRoute
  TopicsTopicIdModulesModuleIdRoute: typeof TopicsTopicIdModulesModuleIdRouteWithChildren
}

const TopicsTopicIdRouteChildren: TopicsTopicIdRouteChildren = {
  TopicsTopicIdFinalExamLevelIdRoute: TopicsTopicIdFinalExamLevelIdRoute,
  TopicsTopicIdModulesModuleIdRoute:
    TopicsTopicIdModulesModuleIdRouteWithChildren,
}

const TopicsTopicIdRouteWithChildren = TopicsTopicIdRoute._addFileChildren(
  TopicsTopicIdRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ProfileRoute: ProfileRoute,
  QuizzesQuizIdRoute: QuizzesQuizIdRoute,
  TopicsTopicIdRoute: TopicsTopicIdRouteWithChildren,
  QuizzesIndexRoute: QuizzesIndexRoute,
  TopicsIndexRoute: TopicsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
