/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as QuizzesIndexRouteImport } from './routes/quizzes.index'
import { Route as LessonsIndexRouteImport } from './routes/lessons.index'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as QuizzesQuizIdRouteImport } from './routes/quizzes.$quizId'
import { Route as LessonsLessonIdRouteImport } from './routes/lessons.$lessonId'
import { Route as AdminQuestionsRouteImport } from './routes/admin/questions'
import { Route as AdminModulesRouteImport } from './routes/admin/modules'
import { Route as AdminLessonsRouteImport } from './routes/admin/lessons'
import { Route as LessonsLessonIdModulesModuleIdRouteImport } from './routes/lessons.$lessonId.modules.$moduleId'
import { Route as LessonsLessonIdFinalExamLevelIdRouteImport } from './routes/lessons.$lessonId.final-exam.$levelId'
import { Route as LessonsLessonIdModulesModuleIdExamRouteImport } from './routes/lessons.$lessonId.modules.$moduleId.exam'
import { Route as LessonsLessonIdModulesModuleIdQuizQuizIdRouteImport } from './routes/lessons.$lessonId.modules.$moduleId.quiz.$quizId'

const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const QuizzesIndexRoute = QuizzesIndexRouteImport.update({
  id: '/quizzes/',
  path: '/quizzes/',
  getParentRoute: () => rootRouteImport,
} as any)
const LessonsIndexRoute = LessonsIndexRouteImport.update({
  id: '/lessons/',
  path: '/lessons/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => rootRouteImport,
} as any)
const QuizzesQuizIdRoute = QuizzesQuizIdRouteImport.update({
  id: '/quizzes/$quizId',
  path: '/quizzes/$quizId',
  getParentRoute: () => rootRouteImport,
} as any)
const LessonsLessonIdRoute = LessonsLessonIdRouteImport.update({
  id: '/lessons/$lessonId',
  path: '/lessons/$lessonId',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminQuestionsRoute = AdminQuestionsRouteImport.update({
  id: '/admin/questions',
  path: '/admin/questions',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminModulesRoute = AdminModulesRouteImport.update({
  id: '/admin/modules',
  path: '/admin/modules',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminLessonsRoute = AdminLessonsRouteImport.update({
  id: '/admin/lessons',
  path: '/admin/lessons',
  getParentRoute: () => rootRouteImport,
} as any)
const LessonsLessonIdModulesModuleIdRoute =
  LessonsLessonIdModulesModuleIdRouteImport.update({
    id: '/modules/$moduleId',
    path: '/modules/$moduleId',
    getParentRoute: () => LessonsLessonIdRoute,
  } as any)
const LessonsLessonIdFinalExamLevelIdRoute =
  LessonsLessonIdFinalExamLevelIdRouteImport.update({
    id: '/final-exam/$levelId',
    path: '/final-exam/$levelId',
    getParentRoute: () => LessonsLessonIdRoute,
  } as any)
const LessonsLessonIdModulesModuleIdExamRoute =
  LessonsLessonIdModulesModuleIdExamRouteImport.update({
    id: '/exam',
    path: '/exam',
    getParentRoute: () => LessonsLessonIdModulesModuleIdRoute,
  } as any)
const LessonsLessonIdModulesModuleIdQuizQuizIdRoute =
  LessonsLessonIdModulesModuleIdQuizQuizIdRouteImport.update({
    id: '/quiz/$quizId',
    path: '/quiz/$quizId',
    getParentRoute: () => LessonsLessonIdModulesModuleIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/login': typeof LoginRoute
  '/profile': typeof ProfileRoute
  '/admin/lessons': typeof AdminLessonsRoute
  '/admin/modules': typeof AdminModulesRoute
  '/admin/questions': typeof AdminQuestionsRoute
  '/lessons/$lessonId': typeof LessonsLessonIdRouteWithChildren
  '/quizzes/$quizId': typeof QuizzesQuizIdRoute
  '/admin/': typeof AdminIndexRoute
  '/lessons/': typeof LessonsIndexRoute
  '/quizzes/': typeof QuizzesIndexRoute
  '/lessons/$lessonId/final-exam/$levelId': typeof LessonsLessonIdFinalExamLevelIdRoute
  '/lessons/$lessonId/modules/$moduleId': typeof LessonsLessonIdModulesModuleIdRouteWithChildren
  '/lessons/$lessonId/modules/$moduleId/exam': typeof LessonsLessonIdModulesModuleIdExamRoute
  '/lessons/$lessonId/modules/$moduleId/quiz/$quizId': typeof LessonsLessonIdModulesModuleIdQuizQuizIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/login': typeof LoginRoute
  '/profile': typeof ProfileRoute
  '/admin/lessons': typeof AdminLessonsRoute
  '/admin/modules': typeof AdminModulesRoute
  '/admin/questions': typeof AdminQuestionsRoute
  '/lessons/$lessonId': typeof LessonsLessonIdRouteWithChildren
  '/quizzes/$quizId': typeof QuizzesQuizIdRoute
  '/admin': typeof AdminIndexRoute
  '/lessons': typeof LessonsIndexRoute
  '/quizzes': typeof QuizzesIndexRoute
  '/lessons/$lessonId/final-exam/$levelId': typeof LessonsLessonIdFinalExamLevelIdRoute
  '/lessons/$lessonId/modules/$moduleId': typeof LessonsLessonIdModulesModuleIdRouteWithChildren
  '/lessons/$lessonId/modules/$moduleId/exam': typeof LessonsLessonIdModulesModuleIdExamRoute
  '/lessons/$lessonId/modules/$moduleId/quiz/$quizId': typeof LessonsLessonIdModulesModuleIdQuizQuizIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/login': typeof LoginRoute
  '/profile': typeof ProfileRoute
  '/admin/lessons': typeof AdminLessonsRoute
  '/admin/modules': typeof AdminModulesRoute
  '/admin/questions': typeof AdminQuestionsRoute
  '/lessons/$lessonId': typeof LessonsLessonIdRouteWithChildren
  '/quizzes/$quizId': typeof QuizzesQuizIdRoute
  '/admin/': typeof AdminIndexRoute
  '/lessons/': typeof LessonsIndexRoute
  '/quizzes/': typeof QuizzesIndexRoute
  '/lessons/$lessonId/final-exam/$levelId': typeof LessonsLessonIdFinalExamLevelIdRoute
  '/lessons/$lessonId/modules/$moduleId': typeof LessonsLessonIdModulesModuleIdRouteWithChildren
  '/lessons/$lessonId/modules/$moduleId/exam': typeof LessonsLessonIdModulesModuleIdExamRoute
  '/lessons/$lessonId/modules/$moduleId/quiz/$quizId': typeof LessonsLessonIdModulesModuleIdQuizQuizIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/login'
    | '/profile'
    | '/admin/lessons'
    | '/admin/modules'
    | '/admin/questions'
    | '/lessons/$lessonId'
    | '/quizzes/$quizId'
    | '/admin/'
    | '/lessons/'
    | '/quizzes/'
    | '/lessons/$lessonId/final-exam/$levelId'
    | '/lessons/$lessonId/modules/$moduleId'
    | '/lessons/$lessonId/modules/$moduleId/exam'
    | '/lessons/$lessonId/modules/$moduleId/quiz/$quizId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/login'
    | '/profile'
    | '/admin/lessons'
    | '/admin/modules'
    | '/admin/questions'
    | '/lessons/$lessonId'
    | '/quizzes/$quizId'
    | '/admin'
    | '/lessons'
    | '/quizzes'
    | '/lessons/$lessonId/final-exam/$levelId'
    | '/lessons/$lessonId/modules/$moduleId'
    | '/lessons/$lessonId/modules/$moduleId/exam'
    | '/lessons/$lessonId/modules/$moduleId/quiz/$quizId'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/login'
    | '/profile'
    | '/admin/lessons'
    | '/admin/modules'
    | '/admin/questions'
    | '/lessons/$lessonId'
    | '/quizzes/$quizId'
    | '/admin/'
    | '/lessons/'
    | '/quizzes/'
    | '/lessons/$lessonId/final-exam/$levelId'
    | '/lessons/$lessonId/modules/$moduleId'
    | '/lessons/$lessonId/modules/$moduleId/exam'
    | '/lessons/$lessonId/modules/$moduleId/quiz/$quizId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  LoginRoute: typeof LoginRoute
  ProfileRoute: typeof ProfileRoute
  AdminLessonsRoute: typeof AdminLessonsRoute
  AdminModulesRoute: typeof AdminModulesRoute
  AdminQuestionsRoute: typeof AdminQuestionsRoute
  LessonsLessonIdRoute: typeof LessonsLessonIdRouteWithChildren
  QuizzesQuizIdRoute: typeof QuizzesQuizIdRoute
  AdminIndexRoute: typeof AdminIndexRoute
  LessonsIndexRoute: typeof LessonsIndexRoute
  QuizzesIndexRoute: typeof QuizzesIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/quizzes/': {
      id: '/quizzes/'
      path: '/quizzes'
      fullPath: '/quizzes/'
      preLoaderRoute: typeof QuizzesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lessons/': {
      id: '/lessons/'
      path: '/lessons'
      fullPath: '/lessons/'
      preLoaderRoute: typeof LessonsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/quizzes/$quizId': {
      id: '/quizzes/$quizId'
      path: '/quizzes/$quizId'
      fullPath: '/quizzes/$quizId'
      preLoaderRoute: typeof QuizzesQuizIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lessons/$lessonId': {
      id: '/lessons/$lessonId'
      path: '/lessons/$lessonId'
      fullPath: '/lessons/$lessonId'
      preLoaderRoute: typeof LessonsLessonIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/questions': {
      id: '/admin/questions'
      path: '/admin/questions'
      fullPath: '/admin/questions'
      preLoaderRoute: typeof AdminQuestionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/modules': {
      id: '/admin/modules'
      path: '/admin/modules'
      fullPath: '/admin/modules'
      preLoaderRoute: typeof AdminModulesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/lessons': {
      id: '/admin/lessons'
      path: '/admin/lessons'
      fullPath: '/admin/lessons'
      preLoaderRoute: typeof AdminLessonsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lessons/$lessonId/modules/$moduleId': {
      id: '/lessons/$lessonId/modules/$moduleId'
      path: '/modules/$moduleId'
      fullPath: '/lessons/$lessonId/modules/$moduleId'
      preLoaderRoute: typeof LessonsLessonIdModulesModuleIdRouteImport
      parentRoute: typeof LessonsLessonIdRoute
    }
    '/lessons/$lessonId/final-exam/$levelId': {
      id: '/lessons/$lessonId/final-exam/$levelId'
      path: '/final-exam/$levelId'
      fullPath: '/lessons/$lessonId/final-exam/$levelId'
      preLoaderRoute: typeof LessonsLessonIdFinalExamLevelIdRouteImport
      parentRoute: typeof LessonsLessonIdRoute
    }
    '/lessons/$lessonId/modules/$moduleId/exam': {
      id: '/lessons/$lessonId/modules/$moduleId/exam'
      path: '/exam'
      fullPath: '/lessons/$lessonId/modules/$moduleId/exam'
      preLoaderRoute: typeof LessonsLessonIdModulesModuleIdExamRouteImport
      parentRoute: typeof LessonsLessonIdModulesModuleIdRoute
    }
    '/lessons/$lessonId/modules/$moduleId/quiz/$quizId': {
      id: '/lessons/$lessonId/modules/$moduleId/quiz/$quizId'
      path: '/quiz/$quizId'
      fullPath: '/lessons/$lessonId/modules/$moduleId/quiz/$quizId'
      preLoaderRoute: typeof LessonsLessonIdModulesModuleIdQuizQuizIdRouteImport
      parentRoute: typeof LessonsLessonIdModulesModuleIdRoute
    }
  }
}

interface LessonsLessonIdModulesModuleIdRouteChildren {
  LessonsLessonIdModulesModuleIdExamRoute: typeof LessonsLessonIdModulesModuleIdExamRoute
  LessonsLessonIdModulesModuleIdQuizQuizIdRoute: typeof LessonsLessonIdModulesModuleIdQuizQuizIdRoute
}

const LessonsLessonIdModulesModuleIdRouteChildren: LessonsLessonIdModulesModuleIdRouteChildren =
  {
    LessonsLessonIdModulesModuleIdExamRoute:
      LessonsLessonIdModulesModuleIdExamRoute,
    LessonsLessonIdModulesModuleIdQuizQuizIdRoute:
      LessonsLessonIdModulesModuleIdQuizQuizIdRoute,
  }

const LessonsLessonIdModulesModuleIdRouteWithChildren =
  LessonsLessonIdModulesModuleIdRoute._addFileChildren(
    LessonsLessonIdModulesModuleIdRouteChildren,
  )

interface LessonsLessonIdRouteChildren {
  LessonsLessonIdFinalExamLevelIdRoute: typeof LessonsLessonIdFinalExamLevelIdRoute
  LessonsLessonIdModulesModuleIdRoute: typeof LessonsLessonIdModulesModuleIdRouteWithChildren
}

const LessonsLessonIdRouteChildren: LessonsLessonIdRouteChildren = {
  LessonsLessonIdFinalExamLevelIdRoute: LessonsLessonIdFinalExamLevelIdRoute,
  LessonsLessonIdModulesModuleIdRoute:
    LessonsLessonIdModulesModuleIdRouteWithChildren,
}

const LessonsLessonIdRouteWithChildren = LessonsLessonIdRoute._addFileChildren(
  LessonsLessonIdRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  LoginRoute: LoginRoute,
  ProfileRoute: ProfileRoute,
  AdminLessonsRoute: AdminLessonsRoute,
  AdminModulesRoute: AdminModulesRoute,
  AdminQuestionsRoute: AdminQuestionsRoute,
  LessonsLessonIdRoute: LessonsLessonIdRouteWithChildren,
  QuizzesQuizIdRoute: QuizzesQuizIdRoute,
  AdminIndexRoute: AdminIndexRoute,
  LessonsIndexRoute: LessonsIndexRoute,
  QuizzesIndexRoute: QuizzesIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
